name: Welcome New Contributors
# Greets people who interact with this repository for the first time. Giving
# them a friendly message when they open their first pull request or issue.

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greet-new-contributors:
    name: Greet new contributors
    runs-on: ubuntu-latest
    steps:
    - name: Post Comment if new contributors
      uses: actions/first-interaction@v3.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        issue_message: >
          Hello @${{ github.actor }}, thanks for opening your first issue.
          Someone will review it soon!
        pr_message: >
          Hello @${{ github.actor }}, thanks for opening your first Pull
          Request. Someone will review it soon!
